name: Node CI

# permissions: 'read-all|write-all'

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm ci
      - name: npm build
        run: npm run build --if-present
        env:
          CI: false
      - name: create new branch for changes
        run: |
            git config --global user.email "github-actions@github.com"
            git config --global user.name "github-actions"
            git checkout -b temp-branch gh-pages
            git add build/*
            git commit -m "Add new build files"
            git push origin temp-branch

      - name: merge changes back into gh-pages
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          git checkout gh-pages
          git pull origin gh-pages
          git merge temp-branch --no-ff -m "Merge new-branch"
          git push origin gh-pages
