name: Node CI

# permissions: 'read-all|write-all'

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm ci
      - name: npm build
        run: npm run build --if-present
        env:
          CI: false
      - name: get local changes
        run: |
          git config --global user.email "oweneisser@gmail.com"
          git config --global user.name "owenpetersen"
          git add .
          git commit -m "Build files"
          git push origin HEAD:gh-pages
      
#       - name: Archive production artifacts
#         uses: actions/upload-artifact@v3
#         with:
#           name: deployment-files
#           path: build
#           retention-days: 1
          
#   move_to_deploy:
#     needs: build
#     runs-on: ubuntu-latest
#     steps:
#       - name: download artifact
#         uses: actions/download-artifact@v3
#         with:
#           name: deployment-files
#       - name: commit to repo
          
