name: Node CI

# permissions: 'read-all|write-all'

on:
  push:
    branches:
    - 'main'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '12.x'
      - name: Install Dependencies
        run: npm ci
      - name: npm build
        run: npm run build --if-present
        env:
          CI: false
      - name: get local changes
        run: |
          git config --global user.email "github-actions@github.com"
          git config --global user.name "github-actions"
          echo "cuhack.it" > build/CNAME
          git add docs/*
          git commit -m "Build files"
          git push
